language: c
dist: trusty
sudo: false

env:
  - COMPILER=clang-3.5
  - COMPILER=clang-4.0
  - COMPILER=gcc-6
  - COMPILER=gcc-5
  - COMPILER=gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-4.0
    packages:
    - gcc-6
    - gcc-5
    - gcc-4
    - clang-3.5
    - clang-4.0
    - protobuf-c-compiler

script:
  - export CC=$COMPILER
  - ./autogen.sh && make -j 4

notifications:
  email: false
