language: c
dist: trusty
sudo: false

env:
  - COMPILER=clang++-3.5
  - COMPILER=clang++-4.0
  - COMPILER=gcc-6
  - COMPILER=gcc-5
  - COMPILER=gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-4.0
    packages:
    - g++-6
    - g++-5
    - g++-4
    - clang-3.5
    - clang-4.0
    - protobuf-c-compiler

script:
  - export CC=$COMPILER
  - libtoolize && aclocal && autoheader && autoconf && automake --add-missing && ./configure && make -j 4

notifications:
  email: false
